require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'RNApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  use_native_modules!
  pod 'RNShineButton', :path => '../node_modules/react-native-shine-button/ios'

  use_frameworks!
  pod 'WCLShineButton',:git => 'https://github.com/tchmhkg/WCLShineButton.git', :branch =>'master'
end
